version: '3.9'

networks:
  issuetracker-network:
    driver: bridge

services:
  issuetracker:
    build:
      context: .
      dockerfile: IssueTracker/Dockerfile
    image: issuetracker
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5279:80"
    networks:
      - issuetracker-network
    depends_on: 
      - postgres
      - redis
  
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - issuetracker-network
    environment:
      - POSTGRES_USER=naotomo
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=E1PsyK0ngr@@
      - POSTGRES_DB=issue_tracker
    volumes:
#      - /var/lib/postgresql/15:/var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql/data
  
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - issuetracker-network
    volumes:
      - redis_data:/var/lib/redis
  
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./IssueTracker/wwwroot:/var/www/static
    ports:
      - "80:80"
    networks:
      - issuetracker-network
    depends_on:
      - issuetracker
volumes:
  postgres_data:
  redis_data:
    